name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.16"
      - run: |
          go vet ./...
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --rm-dist --snapshot
